name: Opam installation
on:
  push:
    paths:
      - '*.opam'
  pull_request:
    paths:
      - '*.opam'

env:
  OPAMYES: true

jobs:
  opam:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-26, windows-2022]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Ocaml with v3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install perl-IPC-System-Simple
        if: runner.os == 'Windows'
        shell: bash
        run: |
          /cygdrive/c/.opam/.cygwin\setup-x86_64.exe \
            --root "C:\\.opam\\.cygwin\\root" \
            --quiet-mode noinput \
            --no-shortcuts \
            --no-startmenu \
            --no-desktop \
            --no-admin \
            --no-version-check \
            --no-write-registry \
            --packages perl-IPC-System-Simple \
            --symlink-type native \
            --upgrade-also \
            --only-site \
            --site https://cygwin.mirror.constant.com/ \
            --local-package-dir "C:\\.opam\\.cygwin\\cache"

      - name: Install geneweb-compat
        run: opam install ./geneweb-compat.opam

      - name: Install geneweb-http
        run: opam install ./geneweb-http.opam

      - name: Install geneweb
        run: opam install ./geneweb.opam

      - name: Install geneweb-rpc
        run: opam install ./geneweb-rpc.opam

      - name: Check binaries
        run: opam exec -- gwd --check
